name: ci-install-packages
on:  
  push:
    branches:
      - main
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install